name: build

on: push

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.12, 1.13]

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Test
        run: env PATH=`go env GOPATH`/bin:$PATH make ci
        env:
          SHELL: /bin/bash
          GOPROXY: "https://proxy.golang.org"
